events {}

http {
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html/public;
            autoindex on;  # opzionale, mostra elenco file
            add_header Access-Control-Allow-Origin *;
        }
    }
}