app.name=apirone

app.owner.name=Apir Srl
app.owner.vat=00000000
app.owner.email=info@apirone.it

app.owner.phone1=+39 389 288 1476
app.owner.city1=San Marino
app.owner.state1=SM
app.owner.zip1=63833
app.owner.address1=Via Delle Rose

app.wirebox.key=wireBox-apirone

server.name=apirone-site
server.port=7073
server.profile=development

mailserver.host=mail.tetilab.me
mailserver.username=sendemail@tetilab.me
mailserver.pwd=ha78,JHq1
mailserver.port=25

email.from=Apir Srl <info@apirone.cc>
email.bcc=roberto.marzialetti@gmail.com
email.subjectPrefix=[Apir Srl]

security.db.encryptKey=pKj12T4KQ5x12vjqQ3SWxLSBCMVC4khJNMxJu1t

verticaledb.host=194.183.87.112
verticaledb.name=verticale
verticaledb.port=1434
verticaledb.pwd=encrypted:d721ad8ece5fda102e2ebca5613f6f3cd0dea73325475de5d1b0bf665a053071
verticaledb.username=sa