app.name=apirone
app.wirebox.key=wireBox-apirone
app.version=100

owner.name=Apir Srl
owner.val=00000000
owner.rmail=info@apirone.it

owner.phone=+39 389 288 1476
owner.city=San Marino
owner.state=SM
owner.zip=63833
owner.address=Via Delle Rose

server.name=apirone-site
server.host=apirone.local
server.port=7110
server.profile=development

mailserver.host=mail.tetilab.me
mailserver.username=sendemail@tetilab.me
mailserver.pwd=ha78,JHq1
mailserver.port=25

email.from=Apir Srl <info@apirone.cc>
email.bcc=roberto.marzialetti@gmail.com
email.subjectPrefix=[Apir Srl]

db.encryptKey=pKj12T4KQ5x12vjqQ3SWxLSBCMVC4khJNMxJu1t

verticaledb.host=194.183.87.112
verticaledb.name=verticale
verticaledb.port=1434
verticaledb.pwd=encrypted:d721ad8ece5fda102e2ebca5613f6f3cd0dea73325475de5d1b0bf665a053071
verticaledb.username=sa

site.main=http://apirone.local:7110
site.repository=http://apirone-repository.local:7112
