{
	defaultIncludes = [
		"id",
		"serial",
		"shortId",
		"referentName",
		"quotationNumber",
		"versionNumber",
		"quotationDate",
		"createdAt",
		"name",
		"active",
		"statusHistory",
		"vatCode",
		"owner.name",
		"owner.shortId"
	],
	profiles = {
		detail = {
			defaultIncludes = [
				"id",
				"serial",
				"shortId",
				"referentName",
				"quotationNumber",
				"versionNumber",
				"quotationDate",
				"name",
				"active",
				"statusHistory",
				"vatCode",
				"lead",
				"lang",
				"customer",
				"opportunity",
				"validityDate",
				"note",
				"paymentMethod",
				"currency",
				"salesAgent",
				"graphicTechnician",
				"shippingProfile",
				"createdAt",
				"owner.name",
				"owner.shortId"
			]
		}
	}
}