UPDATE statuses
SET entities = '["LINE", "ATTRIBUTE", "FINISH", "MODEL", "ACCOUNT", "PRODUCTION_TIME", "PRODUCT_CATEGORY", "PRODUCT", "RAW_VALUE", "METADATA_TYPE", "FRAME", "PRICE_TYPE"]'
WHERE status_id IN ('ACT','DEA');