{
	entities: {
		"ACCOUNT": {},
		"ARTICLE": {},
		"AUTH": {},
		"ATTRIBUTE": {},
		"FONT": {},
		"FONT_FAMILY": {},
		"FONT_FAMILY_SIZE": {},
		"LINE": {},
		"LINECOST": {},
		"LINEMODELCOST": {},
		"MODEL": {},
		"PICTOGRAM": {},
		"PRICE": {},
		"PRICE_TYPE": {},
		"PRODUCT": {},
		"PRODUCT_ITEM": {},
		"QUOTATION": {},
		"RAW_VALUE": {},
		"COMPONENT": {},
		"CATALOG_BUNDLE": {}
	},
	actions: {
		"CREATED": {},
		"UPDATED": {},
		"MULTI_UPDATED": {},
		"DELETED": {},
		"MULTI_DELETED": {},
		"LOGIN": {},
		"FAILED": {},
		"RECOVERY_EMAIL_FAILED": {},
		"LOGOUT": {},
		"VIEWED": {},
		"PAID": {},
		"CLONED": {},
		"CLONED_TREE": {},
		"SEARCH": {},
	}
}
