{
    "Color.bean": {},
    "Country.bean": {},
    "Currency.bean": {},
    "Customer.bean": {},
    "i18n.bean": {},
    "Lang.bean": {},
    "Lead.bean": {},
    "Opportunity.bean": {},
    "PaymentMethod.bean": {},
    "QuotationItemDraft.bean": {},
    "RawProduct.bean": {},
    "RawProductType.bean": {},
    "Status.bean": {},
    "SystemColor.bean": {},
    "Variant.bean": {},
    "VatCode.bean": {},
    "FrameBlock.bean": {},
    "verticale.query": {}
}
