{
    "Account.bean": {},
    "Attribute.bean": {},
    "AttributeValue.bean": {},
    "Color.bean": {},
    "Product.bean": {},
    "Component.bean": {},
    "ComponentOverride.bean": {},
    "Finish.bean": {},
    "Lang.bean": {},
    "Line.bean": {},
    "i18n.bean": {},
    "ProductCategory.bean": {},
    "ProductItem.bean": {},
    "productionTime.bean": {},
    "RawProduct.bean": {},
    "RawProductType.bean": {},
    "RawValue.bean": {},
    "Size.bean": {},
    "Status.bean": {},
    "SystemColor.bean": {},
    "Text.bean": {},
    "Variant.bean": {},
}
