{
    login: [
		{ file: "/modules/assets/template-admin/vendor/jquery/jquery.js" },
		{ file: "/modules/assets/template-admin/vendor/jquery-browser-mobile/jquery.browser.mobile.js" },
        { file: "/assets/main/js/vendor/jquery-validate/jquery.validate.js" },
        { file: "/assets/main/js/vendor/jquery-validate/additional-methods.js" },
    ],

    public: [
        { file: "/modules/assets/template-public/vendor/jquery/jquery.min.js" },
        { file: "/modules/assets/template-public/vendor/jquery.appear/jquery.appear.min.js" },
        { file: "/modules/assets/template-public/vendor/jquery.easing/jquery.easing.min.js" },
        { file: "/modules/assets/template-public/vendor/jquery.cookie/jquery.cookie.min.js" },
        { file: "/modules/assets/template-public/vendor/bootstrap/js/bootstrap.bundle.min.js" },
        { file: "/modules/assets/template-public/vendor/jquery.validation/jquery.validate.min.js" },
        { file: "/modules/assets/template-public/vendor/lazysizes/lazysizes.min.js" },
        { file: "/modules/assets/template-public/vendor/isotope/jquery.isotope.min.js" },
        { file: "/modules/assets/template-public/vendor/owl.carousel/owl.carousel.min.js" },
        { file: "/modules/assets/template-public/vendor/magnific-popup/jquery.magnific-popup.min.js" },
        { file: "/modules/assets/template-public/vendor/vide/jquery.vide.min.js" },
        { file: "/modules/assets/template-public/vendor/vivus/vivus.min.js" },
        { file: "/modules/assets/template-public/js/theme.js" },
        { file: "/modules/assets/template-public/js/views/view.contact.js" },
        { file: "/modules/assets/template-public/js/custom.js" },
        { file: "/modules/assets/template-public/js/theme.init.js" },
    ],
        
    manager: [
        { file: "/modules/assets/template-admin/vendor/jquery/jquery.js" },
        { file: "/modules/assets/template-admin/vendor/jquery-browser-mobile/jquery.browser.mobile.js" },
        { file: "/modules/assets/template-admin/vendor/popper/umd/popper.min.js" },
        { file: "/modules/assets/template-admin/vendor/bootstrap/js/bootstrap.bundle.min.js" },
        { file: "/modules/assets/template-admin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js" },
        { file: "/modules/assets/template-admin/vendor/common/common.js" },
        { file: "/modules/assets/template-admin/vendor/nanoscroller/nanoscroller.js" },
        { file: "/modules/assets/template-admin/vendor/magnific-popup/jquery.magnific-popup.js" },
        { file: "/modules/assets/template-admin/vendor/jquery-placeholder/jquery.placeholder.js" },
        { file: "/modules/assets/template-admin/vendor/jquery-ui/jquery-ui.js" },
        { file: "/modules/assets/template-admin/vendor/jqueryui-touch-punch/jquery.ui.touch-punch.js" },
        { file: "/modules/assets/template-admin/vendor/jquery-appear/jquery.appear.js" },
        { file: "/modules/assets/template-admin/vendor/bootstrapv5-multiselect/js/bootstrap-multiselect.js" },
        { file: "/modules/assets/template-admin/vendor/jquery.easy-pie-chart/jquery.easypiechart.js" },
        { file: "/modules/assets/template-admin/vendor/flot/jquery.flot.js" },
        { file: "/modules/assets/template-admin/vendor/flot.tooltip/jquery.flot.tooltip.js" },
        { file: "/modules/assets/template-admin/vendor/flot/jquery.flot.pie.js" },
        { file: "/modules/assets/template-admin/vendor/flot/jquery.flot.categories.js" },
        { file: "/modules/assets/template-admin/vendor/flot/jquery.flot.resize.js" },
        { file: "/modules/assets/template-admin/vendor/jquery-sparkline/jquery.sparkline.js" },
        { file: "/modules/assets/template-admin/vendor/raphael/raphael.js" },
        { file: "/modules/assets/template-admin/vendor/morris/morris.js" },
        { file: "/modules/assets/template-admin/vendor/gauge/gauge.js" },
        { file: "/modules/assets/template-admin/vendor/snap.svg/snap.svg.js" },
        { file: "/modules/assets/template-admin/vendor/liquid-meter/liquid.meter.js" },
        { file: "/modules/assets/template-admin/vendor/pnotify/pnotify.custom.js" },
        { file: "/modules/assets/template-admin/vendor/bootstrap-maxlength/bootstrap-maxlength.js" },
        { file: "/modules/assets/template-admin/js/theme.js" },
        { file: "/modules/assets/template-admin/js/custom.js" },
        { file: "/modules/assets/template-admin/js/theme.init.js" },
        { file: "/modules/assets/template-admin/js/examples/examples.dashboard.js" },

        { file: "/assets/main/js/vendor/jquery-validate/jquery.validate.js" },
        { file: "/assets/main/js/vendor/jquery-validate/additional-methods.js" },

    ]
}